# Generated by Django 6.0.4 on 2026-04-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Role',
            new_name='role',
        ),
    ]
