# Generated by Django 6.0.4 on 2026-04-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookingapp', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10)),
                ('room_name', models.CharField(max_length=100)),
                ('room_capacity', models.CharField(max_length=100)),
                ('room_info', models.CharField(max_length=100)),
            ],
        ),
    ]
