# Generated by Django 6.0.4 on 2026-04-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookingapp', '0004_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
