# Generated by Django 6.0.4 on 2026-04-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookingapp', '0005_alter_room_room_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10)),
                ('booking_type', models.CharField(max_length=100)),
                ('date_start', models.CharField(max_length=100)),
                ('date_end', models.CharField(max_length=100)),
                ('week_type', models.CharField(max_length=100)),
                ('time_start', models.CharField(max_length=100)),
                ('time_end', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
    ]
