# Generated by Django 6.0.4 on 2026-04-28 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookingapp', '0006_booking_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingForSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('subject', 'สอนปกติ/ชดเชย/เสริม'), ('tutoring', 'จัดอบรม/จัดติว')], max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('days_of_week', models.CharField(default='', max_length=200)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('username', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('curriculum', models.CharField(choices=[('ปริญญาตรีภาคปกติ', 'ปริญญาตรีภาคปกติ'), ('ปริญญาโท', 'ปริญญาโท'), ('TEP-TEPE', 'TEP-TEPE'), ('TU-PINE', 'TU-PINE')], max_length=100)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_room', to='Bookingapp.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingForTutoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('subject', 'สอนปกติ/ชดเชย/เสริม'), ('tutoring', 'จัดอบรม/จัดติว')], max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('days_of_week', models.CharField(default='', max_length=200)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=500)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_room', to='Bookingapp.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
