# Generated by Django 6.0.4 on 2026-04-28 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookingapp', '0007_bookingforsubject_bookingfortutoring_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingforsubject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingforsubject',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingforsubject',
            name='decided_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingforsubject',
            name='denial_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='bookingforsubject',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bookingforsubject',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bookingforsubject',
            name='status',
            field=models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingfortutoring',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingfortutoring',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingfortutoring',
            name='decided_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingfortutoring',
            name='denial_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='bookingfortutoring',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bookingfortutoring',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bookingfortutoring',
            name='status',
            field=models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Blackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='Bookingapp.room')),
            ],
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                apps.get_model('Bookingapp', 'BookingForSubject').objects.update(status='approved'),
                apps.get_model('Bookingapp', 'BookingForTutoring').objects.update(status='approved'),
            ),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
