# Generated by Django 6.0.4 on 2026-04-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookingapp', '0009_seed_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
